#!/usr/bin/python3
# Usage:
#   ./ImpedancePlot file1.csv file2.csv
#   ./Impedance -s "XXXXXXXXXXXXXXXX" -t 21.6 -u 0.37 xml/ModernFlute.xml | ./ImpedancePlot 
import matplotlib.pyplot as plt
import numpy as np
import sys
from math import sqrt
from operator import add
import pandas as pd
import io

if __name__ == "__main__":
    fig = plt.figure()
    e = sys.argv[1:]
    if len(e) == 0:
        e = ['stdin']
        stdin = ""
        for line in sys.stdin:
            stdin += line
    for n, f in enumerate(e):
        if f == 'stdin':
            csv = pd.read_csv(io.StringIO(stdin), header=None, sep='\t')
        else:
            csv = pd.read_csv(f, header=None, sep='\t')
        freq = csv[0]
        zr = csv[1]
        zi = csv[2]
        zrsq = list(map(lambda n: n ** 2, zr))
        zisq = list(map(lambda n: n ** 2, zi))
        z = list(map(add, zrsq, zisq))
        z = list(map(lambda n: sqrt(n), z))

        ax = fig.add_subplot(1, 1, 1)
        ax.plot(freq, z, label=f)
        ax.set(xlabel='Frequency (kHz)', ylabel='|Z| (Pa s m−3)')
        r = range(0, int(max(freq)) + 1, 1000)
        ax.set_xticks(r)
        ax.set_xticklabels([str(int(x/1000)) for x in r])
        r = np.logspace(4, 8, 5)
        ax.set_yticklabels([str(x) for x in r])
        ax.set_ylim([10e3, 10e7])
        ax.set_yscale('log')
        plt.legend()

    plt.show()

