#!/usr/bin/python3
# Usage:
#   ./PlayedImpedancePlot file.csv
#   ./PlayedImpedance template/KavalSib xml/ModernFlute.xml | ./ImpedancePlot 
import matplotlib.pyplot as plt
import numpy as np
import sys
from math import sqrt
from operator import add
import pandas as pd
import io

if __name__ == "__main__":
    fig = plt.figure()
    e = sys.argv[1:]
    if len(e) == 0:
        e = ['stdin']
        stdin = ""
        for line in sys.stdin:
            stdin += line
    for n, f in enumerate(e):
        if f == 'stdin':
            csv = pd.read_csv(io.StringIO(stdin), header=None, sep='\t')
        else:
            csv = pd.read_csv(f, header=None, sep='\t')
        freq = csv[0][1:]
        print(csv)
        ax = fig.add_subplot(1, 1, 1)
        for i in range(1, len(csv.columns)):
            ax.plot(freq, csv[i][1:], label=str(csv[i][0]))
        ax.set(xlabel='Frequency (Hz)', ylabel='20 log_10 (|Z| / Z0) (Z0 = 1 Pa s m−3)')
        plt.legend()

    plt.show()

